const styles = [
  "Psychedelic",
  "Surrealism",
  "3D illustration",
  "Geometric",
  "Retro",
  "Vintage",
  "Realism",
  "Synthwave",
  "Abstract",
  "Pop Art",
  "Minimalism",
  "Impressionism",
  "Art Deco",
  "Art Nouveau",
  "Expressionism",
  "Cubism",
  "Romanticism",
  "Baroque",
  "Renaissance",
  "Neoclassicism",
  "Mannerism",
  "Rococo",
  "Post-Impressionism",
  "Sketch",
  "Oil Painting",
  "Watercolor",
  "Comic Book",
  "Pen and Ink",
  "Cartoon",
  "Realistic",
  "Abstract",
  "Graffiti",
  "Pixelated",
  "Mosaic",
  "Pointillism",
  "Charcoal",
  "Chalk",
  "Collage",
];
export default styles;
