import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { signIn } from "next-auth/react";
import { useSession } from "next-auth/react";
import {
  Button,
  Checkbox,
  FormControlLabel,
  Paper,
  TextField,
} from "@mui/material";
import LockIcon from "@mui/icons-material/Lock";

const inter = Inter({ subsets: ["latin"] });

export default function Login(props: any) {
  const { data: session, status } = useSession();
  session?.user?.image;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <body className="white"></body>
      </Head>
      <main>
        {session?.user?.email}
        {status}
        <div className="container mx-auto justify-center h-screen items-center flex ">
          <Paper className="h-auto p-10 py-7 w-1/3" elevation={3}>
            <div className="p-5 pt-0">
              <div className="text-center">
                <LockIcon
                  className="text-center"
                  sx={{ fontSize: 40, color: "darkblue" }}
                />
              </div>
              <h1 className="text-2xl text-center font-semibold">Sign in</h1>
              <TextField
                className="w-full mt-7"
                label="Email"
                type="email"
                variant="outlined"
              ></TextField>
              <TextField
                className="w-full mt-7"
                label="Password"
                type="password"
                variant="outlined"
              ></TextField>
              <FormControlLabel
                className="mt-3"
                control={<Checkbox />}
                label="Remember me"
              />
              <Button
                className="w-full mt-7 bg-blue-900"
                color="primary"
                variant="contained"
              >
                Sign in
              </Button>
              <Button
                className="w-full mt-7 bg-blue-900"
                color="primary"
                variant="contained"
                onClick={() => signIn()}
              >
                Sign in with GitHub
              </Button>
            </div>
          </Paper>
        </div>
      </main>
    </>
  );
}
